# Generated by Django 3.2.6 on 2021-08-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
