# Generated by Django 3.2.6 on 2021-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210803_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
