# Generated by Django 3.2.6 on 2021-08-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='place',
        ),
    ]
